name: python-data
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - dask
  - matplotlib
  - plotly
  - jupyterlab
  - ipywidgets
  - tqdm
  - pytables
  - lxml
  - pyarrow=11.0.0
  - pip
  - pip:
      - streamlit
      - pandarallel
      - ipython-autotime
      - chart-studio
