name: data-structure
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - plotly
  - sqlalchemy
  - jupyterlab
  - tqdm
  - fastapi
  - uvicorn
  - pytorch
  - torchvision
  - python-multipart
  - pytables
  - lxml
  - pyarrow=11.0.0
  - pip
  - pip:
      - streamlit
