name: python-data-serialization
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - plotly
  - jupyterlab
  - pytables
  - lxml
  - pyarrow=11.0.0
  - pip
  - pip:
      - tqdm
      - chart-studio
